### ISSUE TITLE
h_masked for embedding?

### ISSUE THREAD

**Issue by bryanbocao** [dapowan/LIMU-BERT-Public#5]
Hi @dapowan,

One more clarification question: When we only need to generate the embeddings, we set ```output_embed=True```, and therefore the ```h_masked``` is essentially a ```h``` that is the embedding output without any masking?
https://github.com/dapowan/LIMU-BERT-Public/blob/a355baa15e5338de71b3268a45dd9767a04aa3d8/models.py#L171

```h``` is for masked sequences (which is ```h_masked```) only when ```output_embed=False``` and ```masked_pos``` is provided.
https://github.com/dapowan/LIMU-BERT-Public/blob/a355baa15e5338de71b3268a45dd9767a04aa3d8/models.py#L175

Thanks!

**Comment by dapowan** [comment]
Yes.
